name: jeriko
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage: 2.1.1
  google_fonts: 6.2.1
  firebase_core: 3.1.0
  cloud_firestore: 5.0.1
  firebase_storage: 12.0.1
  uuid: 4.4.0
  intl: 0.19.0
  geolocator: 12.0.0
  geocoding: 3.0.0
  image_picker: 1.1.2
  flutter_map: 7.0.1
  latlong2: 0.9.1
  http: 1.2.1
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true
flutter_launcher_icons:
  android: "jeriko_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"

